/** English UI strings — default locale for Suki games. */

export const en = {
  balance: 'Balance',
  bet: 'Bet',
  win: 'Win',
  betAmount: 'Bet amount',
  lastResult: 'Last result',
  sessionBestWin: 'Session best',
  drop: 'Drop',
  playVerb: 'play',
  insufficientBalance: 'Insufficient Funds.',
  setBetPrompt: 'Set bet · press Drop.',
  connectingRgs: 'Connecting to RGS…',
  sessionPl: 'Session P/L',
  sessionPlays: 'Session plays',
  replayNote: 'Recorded round — not a live bet',
  replayModeTitle: 'Replay mode',
  replayDisclaimer:
    'Recorded round for review only. No live bet is placed and your balance will not change.',
  stakeReturned: 'push, stake returned',
  won: 'won',
  onAmount: 'on',
  newSessionBalance: 'New session — balance',
  autoplayStopped: 'Autoplay stopped — insufficient balance after',
  autoplayButton: 'Autoplay',
  autoplayTitle: 'Autoplay',
  autoplaySummary: 'Choose how many rounds to play automatically at your current bet.',
  autoplayRoundsLabel: 'Number of rounds',
  autoplayCustomRoundsLabel: 'Custom rounds',
  autoplayCostLine: 'Cost per round: {playCost}',
  autoplayStart: 'Start autoplay',
  autoplayCancel: 'Cancel',
  autoplayProgress: 'Autoplay {current}/{total}…',
  autoplayComplete: 'Autoplay complete — {count} plays.',
  connectionLost: 'Connection lost',
  connectionRetry: 'Retry',
  invalidRgsConnection:
    'Unable to connect — game connection settings are invalid. Reopen the game from Stake.',
  replayAgain: 'Replay again',
  loadingReplay: 'Loading replay…',
  replayingRound: 'Replaying round…',
  replayPlayLabel: 'Play cost',
  payoutMultiplierLabel: 'Payout multiplier',
  replayFinalAmountLabel: 'Final amount',
  baseBetLabel: 'Base bet',
  costMultiplierLabel: 'Cost multiplier',
  playModeLabel: 'Play mode',
  modeLabelBase: 'Base',
  modeLabelBuy: 'Buy bonus ×{mult}',
  modeLabelActivate: 'Ante ×{mult}',
  modeInfoBase: 'Base',
  buyPlayButton: 'Buy & play',
  buyFeatureDisabledHint: 'Buy feature disabled for this jurisdiction',
  buyConfirmTitle: 'Buy bonus',
  buyConfirmSummary:
    'You are purchasing the bonus feature at {costMult}× your base bet. The full amount is charged when you confirm.',
  buyConfirmFeatureDetail:
    '8 free spins are awarded. Wins during the feature are added to your balance when the round ends.',
  buyConfirmTotalLabel: 'Total cost',
  buyConfirmCancel: 'Cancel',
  modeCostLine:
    '{playLabel}: {playCost} — {baseLabel}: {baseAmount} × {multLabel} {costMult}',
  replayStartSummary:
    '{playLabel}: {playAmount} · {worthLabel}: {worthMult} · {finalLabel}: {finalAmount}',
  gamblingLimitReached: 'Gambling limit reached.',
  roundingNote:
    'Balance is displayed rounded to 2 decimal places. Win amounts show the full value received from the Remote Game Server.',
  generalDisclaimerTitle: 'General Disclaimer',
  generalDisclaimer:
    'Malfunction voids all wins and plays. A consistent internet connection is required. In the event of a disconnection, reload the game to finish any uncompleted rounds. The expected return is calculated over many plays. The game display is not representative of any physical device and is for illustrative purposes only. Winnings are settled according to the amount received from the Remote Game Server and not from events within the web browser. TM and © 2026 Stake Engine.',
  maxWinLabel: 'Max win',
  rtpLabel: 'RTP',
  howToPlayIntro:
    'Choose a {betTerm} and press {drop}. One ball, one bucket — the payout is decided before the animation runs.',
  howToPlayBullet1: 'No row picker or risk sliders — single preset only.',
  howToPlayBullet2: 'Paytable is always visible under the board.',
  howToPlayBullet3: 'Spacebar drops when allowed by jurisdiction.',
  paytableBucketCol: 'Bucket',
  paytableMultiplierCol: 'Multiplier',
  paytableMenuLabel: 'Paytable',
  paytableTitle: 'Paytable',
  statsNotShown: 'Session stats are not shown for this jurisdiction.',
  statsPlays: 'Plays',
  statsBestWin: 'Best win',
  statsAvgReturn: 'Avg return',
  recentResultsEmpty: 'No drops yet — play to populate history.',
};

/** Social casino overrides for English (stake.us-style terminology). */
export const enSocial = {
  bet: 'Play',
  win: 'Earn',
  betAmount: 'Play amount',
  insufficientBalance: 'Insufficient Balance.',
  setBetPrompt: 'Set play amount · press Drop.',
  connectingRgs: 'Connecting…',
  replayNote: 'Recorded round — not a live play',
  replayModeTitle: 'Replay mode',
  replayDisclaimer:
    'Recorded round for review only. No live play is made and your balance will not change.',
  stakeReturned: 'push, play amount returned',
  autoplayStopped: 'Autoplay stopped — insufficient balance after',
  replayPlayLabel: 'Play amount',
  payoutMultiplierLabel: 'Final multiplier',
  baseBetLabel: 'Base Play',
  costMultiplierLabel: 'Feature Multiplier',
  modeLabelBase: 'Base Play',
  modeLabelBuy: 'Feature ×{mult}',
  modeLabelActivate: 'Extra ×{mult}',
  modeInfoBase: 'Base Play',
  buyPlayButton: 'Play feature',
  buyFeatureDisabledHint: 'Feature disabled for this jurisdiction',
  buyConfirmTitle: 'Play feature',
  buyConfirmSummary:
    'You are activating the feature at {costMult}× your base play amount. The full amount is charged when you confirm.',
  buyConfirmFeatureDetail:
    '8 free spins are awarded. Wins during the feature are added to your balance when the round ends.',
  buyConfirmTotalLabel: 'Total play amount',
  buyConfirmCancel: 'Cancel',
  gamblingLimitReached: 'Play limit reached.',
  roundingNote:
    'Balance is displayed rounded to 2 decimal places. Earn amounts show the full value received from the Remote Game Server.',
  paytableMenuLabel: 'Win table',
  paytableTitle: 'Win table',
  howToPlayIntro:
    'Choose a play amount and press {drop}. One ball, one bucket — the win amount is decided before the animation runs.',
};
