/** English UI strings — default locale for Suki games. */

export const en = {
  balance: 'Balance',
  bet: 'Bet',
  betAmount: 'Bet amount',
  lastResult: 'Last result',
  drop: 'Drop',
  playVerb: 'play',
  insufficientBalance: 'Insufficient Funds.',
  setBetPrompt: 'Set bet · press Drop.',
  connectingRgs: 'Connecting to RGS…',
  sessionPl: 'Session P/L',
  sessionPlays: 'Session plays',
  replayNote: 'Recorded round — not a live bet',
  stakeReturned: 'push, stake returned',
  won: 'won',
  onAmount: 'on',
  newSessionBalance: 'New session — balance',
  autoplayStopped: 'Autoplay stopped — insufficient balance after',
  autoplayButton: 'Autoplay',
  autoplayTitle: 'Autoplay',
  autoplaySummary: 'Choose how many rounds to play automatically at your current bet.',
  autoplayRoundsLabel: 'Number of rounds',
  autoplayCostLine: 'Cost per round: {playCost}',
  autoplayStart: 'Start autoplay',
  autoplayCancel: 'Cancel',
  autoplayProgress: 'Autoplay {current}/{total}…',
  autoplayComplete: 'Autoplay complete — {count} plays.',
  connectionLost: 'Connection lost',
  connectionRetry: 'Retry',
  invalidRgsConnection:
    'Unable to connect — game connection settings are invalid. Reopen the game from Stake.',
  replayAgain: 'Replay again',
  loadingReplay: 'Loading replay…',
  replayingRound: 'Replaying round…',
  replayPlayLabel: 'Play cost',
  payoutMultiplierLabel: 'Payout multiplier',
  replayFinalAmountLabel: 'Final amount',
  baseBetLabel: 'Base bet',
  costMultiplierLabel: 'Cost multiplier',
  playModeLabel: 'Play mode',
  modeCostLine:
    '{playLabel}: {playCost} — {baseLabel}: {baseAmount} × {multLabel} {costMult}',
  replayStartSummary:
    '{playLabel}: {playAmount} · {worthLabel}: {worthMult} · {finalLabel}: {finalAmount}',
  gamblingLimitReached: 'Gambling limit reached.',
  roundingNote: 'All displayed amounts are rounded to 2 decimal places.',
  maxWinLabel: 'Max win',
  rtpLabel: 'RTP',
  howToPlayIntro:
    'Choose a {betTerm} and press {drop}. One ball, one bucket — the payout is decided before the animation runs.',
  howToPlayBullet1: 'No row picker or risk sliders — single preset only.',
  howToPlayBullet2: 'Paytable is always visible under the board.',
  howToPlayBullet3: 'Spacebar drops when allowed by jurisdiction.',
  paytableBucketCol: 'Bucket',
  paytableMultiplierCol: 'Multiplier',
  statsNotShown: 'Session stats are not shown for this jurisdiction.',
  statsPlays: 'Plays',
  statsBestWin: 'Best win',
  statsAvgReturn: 'Avg return',
  recentResultsEmpty: 'No drops yet — play to populate history.',
};

/** Social casino overrides for English (stake.us-style terminology). */
export const enSocial = {
  balance: 'Coins',
  bet: 'Play',
  betAmount: 'Play amount',
  insufficientBalance: 'Insufficient Balance.',
  setBetPrompt: 'Set play amount · press Drop.',
  connectingRgs: 'Connecting…',
  sessionPl: 'Session coins',
  replayNote: 'Recorded round — not a live play',
  stakeReturned: 'push, play amount returned',
  newSessionBalance: 'New session — coins',
  autoplayStopped: 'Autoplay stopped — insufficient balance after',
  replayPlayLabel: 'Play amount',
  payoutMultiplierLabel: 'Final multiplier',
  baseBetLabel: 'Base Play',
  costMultiplierLabel: 'Feature Multiplier',
  gamblingLimitReached: 'Play limit reached.',
  howToPlayIntro:
    'Choose a play amount and press {drop}. One ball, one bucket — the win amount is decided before the animation runs.',
};
